# Generated by Django 3.2.16 on 2023-03-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_det',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_det', models.CharField(max_length=225)),
                ('academic_year', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='occation',
            fields=[
                ('occation_id', models.AutoField(primary_key=True, serialize=False)),
                ('occation_det', models.CharField(max_length=225)),
                ('occation_date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('dob', models.CharField(max_length=225)),
                ('doa', models.CharField(max_length=225)),
                ('academic_year', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='static/media')),
                ('date', models.CharField(max_length=225)),
                ('mark', models.CharField(max_length=225)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=225)),
                ('p1_id', models.CharField(max_length=225)),
                ('p2_id', models.CharField(max_length=225)),
                ('p3_id', models.CharField(max_length=225)),
                ('p4_id', models.CharField(max_length=225)),
                ('p5_id', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=225)),
                ('result', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=225)),
                ('notes', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fees', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='class_assign',
            fields=[
                ('class_assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=225)),
                ('assignment', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('class_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class_det')),
            ],
        ),
    ]
