# Generated by Django 3.2.16 on 2023-03-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
            preserve_default=False,
        ),
    ]
