# Generated by Django 3.2.16 on 2023-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_note_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_title', models.CharField(max_length=225)),
                ('expense_amount', models.CharField(max_length=225)),
                ('expense_date', models.CharField(max_length=225)),
            ],
        ),
    ]
