# Generated by Django 3.2.16 on 2023-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fee_fees_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
